# Site settings
title: Felipe García
tagline: Student at École Polytechnique
email: felipe.garcia@polytechnique.edu
description: Felipe Garcia homesite about quantitative finance mathematics statistics and misc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://felipeandresg.github.io" # the base hostname & protocol for your site

#twitter_username: felipe???

github_username:  felipeandresg
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
